appointments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^dashboard/', include('apps.appts_app.urls', namespace='appts_stuff')),
    url(r'^', include('apps.login_and_reg_app.urls', namespace='login_stuff'))
]

apps/appts_app/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='destroy'),
    url(r'^appointments/(?P<id>\d+)$', views.edit, name='edit'),
    url(r'^update/(?P<id>\d+)$', views.update, name='update'),
]

apps/login_and_reg_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='my_index'),
    url(r'^register$', views.register, name='my_register'),
    url(r'^login$', views.login, name='my_login'),
    url(r'^success$', views.success, name='my_success'),
    url(r'^logout$', views.logout, name='my_logout'),
]

apps/appts_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_and_reg_app.models import User

class Appointment(models.Model):
    task = models.CharField(max_length=1000)
    date = models.CharField(max_length=1000)
    time = models.CharField(max_length=45)
    status = models.CharField(max_length=45, default='pending')
    user = models.ForeignKey(User, related_name='appointments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/login_and_reg_app/models.py
from __future__ import unicode_literals
from django.db import models
import re, bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def login(self, postData):
        user = self.filter(email=postData['email'])
        response_to_views = {}
        if not user:
            response_to_views['status'] = False
            response_to_views['errors'] = 'Email address not valid'

        else:
            if bcrypt.checkpw(postData['password'].encode(), user[0].password.encode()):
                response_to_views['status'] = True
                response_to_views['user'] = user[0]

            else:
                response_to_views['status'] = False
                response_to_views['errors'] = 'Email/password combination not valid'

        return response_to_views

    def register(self, postData):
        errors = []
        if len(postData['name']) < 3:
            errors.append('Name must be at least 3 characters long!')
        if len(postData['email']) < 1:
            errors.append('Email field cannot be empty')
        if not EMAIL_REGEX.match(postData['email']):
            errors.append("Enter a valid email")
        if len(postData['password']) < 8:
            errors.append('Password must contain at least 8 characters')
        if postData['password'] != postData['pwd_conf']:
            errors.append('Passwords do not match')
        if self.filter(email=postData['email']):
            errors.append('Email already in use')

        response_to_views = {}
        if len(errors) == 0:
            hashed_password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
            user = self.create(name=postData['name'], email=postData['email'], password=hashed_password)
            response_to_views['user'] = user
            response_to_views['status'] = True

        else:
            response_to_views['errors'] = errors
            response_to_views['status'] = False

        return response_to_views
class User(models.Model):
    name = models.CharField(max_length=45)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()
      

apps/appts_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from datetime import date
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import Appointment
from ..login_and_reg_app.models import User

def index(request):
    if not 'user_id' in request.session:
        messages.error(request, 'must be logged in to continue')
        return redirect(reverse('login_stuff:my_index'))
    request.session['user_name']
    curr_user = User.objects.get(name=request.session['user_name'])
    context= {
        'myappts': Appointment.objects.filter(user=curr_user),
        'date_now': date.today()
    }
    return render(request, 'appts_app/dashboard.html', context)

def add(request):
    if len(request.POST['date']) < 1:
        messages.error(request, 'Date Field cannot be empty')
        return redirect('/dashboard')
    if len(request.POST['time']) < 1:
        messages.error(request, 'Time Field cannot be empty')
        return redirect('/dashboard')
    if len(request.POST['task']) < 1:
        messages.error(request, 'Task Field cannot be empty')
        return redirect('/dashboard')
    if Appointment.objects.filter(date=request.POST['date']).filter(time=request.POST['time']):
        messages.error(request, 'Date/time already in use')
        return redirect('/dashboard')

    else:
        curr_user = User.objects.get(name=request.session['user_name'])
        Appointment.objects.create(task=request.POST['task'], date=request.POST['date'], time=request.POST['time'], user=curr_user)
        return redirect('/dashboard')

def delete(request, id):
    Appointment.objects.filter(id=id).delete()
    return redirect('/dashboard')

def edit(request, id):
    context = {
        'appts': Appointment.objects.filter(id=id)
    }
    return render(request, 'appts_app/edit.html', context)

def update(request, id):
    if len(request.POST['task']) < 1:
        context = {
            'appts': Appointment.objects.filter(id=id)
        }
        messages.error(request, 'Task Field cannot be empty')
        return render(request, 'appts_app/edit.html', context)
    if len(request.POST['date']) < 1:
        context = {
            'appts': Appointment.objects.filter(id=id)
        }
        messages.error(request, 'Date Field cannot be empty')
        return render(request, 'appts_app/edit.html', context)
    if len(request.POST['time']) < 1:
        context = {
            'appts': Appointment.objects.filter(id=id)
        }
        messages.error(request, 'Time Field cannot be empty')
        return render(request, 'appts_app/edit.html', context)
    else:
        appt = Appointment.objects.get(id=id)
        appt.task = request.POST['task']
        appt.status = request.POST['status_options']
        appt.date = request.POST['date']
        appt.time = request.POST['time']
        appt.save()
        return redirect(reverse('appts_stuff:index'))

apps/login_and_reg_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

def index(request):
    return render(request, 'login_and_reg_app/index.html')

def register(request):
    response_from_model = User.objects.register(request.POST)

    if response_from_model['status']:
        request.session['user_id'] = response_from_model['user'].id
        request.session['user_name'] = response_from_model['user'].name
        return redirect(reverse('appts_stuff:index'))

    else:
        for error in response_from_model['errors']:
            messages.error(request, error)
        return redirect(reverse('login_stuff:my_index'))
def login(request):
    response_from_model = User.objects.login(request.POST)
    if response_from_model['status']:
        request.session['user_id'] = response_from_model['user'].id
        request.session['user_name'] = response_from_model['user'].name
        return redirect(reverse('appts_stuff:index'))

    else:
        messages.error(request, response_from_model['errors'])
        return redirect(reverse('login_stuff:my_index'))

def success(request):
    if not 'user_id' in request.session:
        messages.error(request, 'must be logged in to continue')
        return redirect(reverse('login_stuff:my_index'))
    return redirect(reverse('appts_stuff:index'))

def logout(request):
    request.session.clear()
    return redirect(reverse('login_stuff:my_index'))

apps/appts_app/templates/appts_app/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Welcome</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'appts_app/style.css' %}">
    </head>
    <body>
        <h1>Hello, {{request.session.user_name}}!</h1>
        <div class="today">
          <h3>Here are your appointments for Today, {{ date_now }}: </h3>
          <table>
              <tr>
                  <th>Tasks</th>
                  <th>Time</th>
                  <th>Status</th>
                  <th>Action</th>
              </tr>
              {% for appt in myappts %}
                  {% if appt.date == '2017-11-27' %}
              <tr>
                  <td>{{appt.task}}</td>
                  <td>{{appt.time}}</td>
                  <td>{{appt.status}}</td>
                  <td><a href="{%url 'appts_stuff:edit' id=appt.id %}">Edit</a> | <a href="{%url 'appts_stuff:destroy' id=appt.id %}">Delete</a></td>
              </tr>
                  {% endif %}
              {% endfor %}
          </table>
        </div>
        <div class="other">
          <h3>Here are your other appointments:</h3>
          <table>
              <tr>
                  <th>Tasks</th>
                  <th>Date</th>
                  <th>Time</th>
              </tr>
              {% for appt in myappts %}
                  {% if appt.date != '2017-11-27' %}
              <tr>
                  <td>{{appt.task}}</td>
                  <td>{{appt.date}}</td>
                  <td>{{appt.time}}</td>
              </tr>
                  {% endif %}
              {% endfor %}
          </table>
        </div>
        <div class="add">
          <h2>Add Appointment:</h2>
          {% if messages %}
              {% for message in messages %}
              <p>{{ message }}</p>
              {% endfor %}
          {% endif %}
          <form action="{%url 'appts_stuff:add' %}" method="post">
              {% csrf_token %}
              <p><label for="date">Date: </label><input type="date" name="date" min="2017-11-27"></p>
              <p><label for="time">Time: (must be entered HH:MM and AM/PM) </label><input type="time" name="time"></p>
              <p><label for="task">Task: </label><input type="text" name="task"></p>
              <p><input type="submit" name="submit" value="Add"></p>
          </form>
          <p><a href="{%url 'login_stuff:my_logout' %}">Logout</a></p>
        </div>
    </body>
</html>

apps/appts_app/templates/appts_app/edit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Update Appointment</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'appts_app/style.css' %}">
    </head>
    <body>
        {% if messages %}
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
        {% for appt in appts %}
        <h1>Edit Appointment {{appt.id}}</h1>
        <form action="{%url 'appts_stuff:update' id=appt.id %}" method="POST">
            {% csrf_token %}
            <p><label for="task">Task:</label></p>
            <p><input type="text" name="task" value={{appt.task}}></p>
            <p><label for="status">Status:</label></p>
            <select name="status_options">
              <option value="Pending">Pending</option>
              <option value="Done">Done</option>
              <option value="Missed">Missed</option>
            </select>
            <p><label for="date">Date:</label></p>
            <p><input type="date" name="date" min="2017-11-27" value={{appt.date}}></p>
            <p><label for="time">Time:</label></p>
            <p><input type="time" name="time" value={{appt.time}}></p>
            <p><input type="submit" name="submit" value="Update"></p>
        </form>
        {% endfor %}
        <a href="{%url 'appts_stuff:index' %}">Home</a>
        <a href="{%url 'login_stuff:my_logout' %}">Logout</a>
    </body>
</html>

apps/login_and_reg_app/templates/login_and_reg_app/index.html
<html>

<head>
    <title>Login/Registration</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'login_and_reg_app/style.css' %}">
</head>

<body>
    <h1>Welcome!</h1>
    <div class="register">
      <h3>Register</h3>
      {% if messages %}
          {% for message in messages %}
          <p>{{ message }}</p>
          {% endfor %}
      {% endif %}
      <form class="forms" action="{%url 'login_stuff:my_register' %}"  method='POST'>
      {% csrf_token %}
          <p><label for="name">Name: <input type="text" name="name"></label></p>
          <p><label for="email">Email: <input type="text" name="email"></label></p>
          <p><label for="password">Password: <input type="password" name="password"></label></p>
          <p><label for="password_conf">Confirm Password: <input type="password" name="pwd_conf"></label></p>
          <p><label for="dob">Date of Birth: <input type="date" name="date"></label></p>
          <p id="button"><input type="submit" value="Register"></p>
      </form>
    </div>
    <div class="login">
      <h3>Login</h3>

      <form class="forms" action="{%url 'login_stuff:my_login' %}"  method='POST'>
      {% csrf_token %}
          <p><label for="email">Email: <input type="text" name="email" id="email"></label></p>
          <p><label for="password">Password: <input type="password" name="password" id="password"></label></p>
          <p id="button"><input type="submit" value="Login"></p>
      </form>
    </div>
</body>
</html>

apps/login_and_reg_app/templates/login_and_reg_app/success.html
<!DOCTYPE>
<html>
    <head>
      {% load static %}
      <link rel="stylesheet" href="{% static 'login_and_reg_app/style.css' %}">
    </head>
    <body>
        <h1>You have successfully registered!</h1>
        {{request.session.user_id}}
        {{request.session.user_name}}
        <form action="{%url 'my_logout' %}"  method='post'>
            {% csrf_token %}
            <input type="submit" name="logout" value="Logout">
        </form>
    </body>
</html>